#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update -y update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ervice nginx start
