#!/usr/bin/env bash

# Update apt package index
sudo apt update

# Install nginx
sudo apt install -y nginx

# Configure nginx
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;
    location / {
        return 200 "Hello World!";
    }
}
EOF'

# Test nginx configuration
sudo nginx -t

# Reload nginx
sudo nginx -s reload
