#!/usr/bin/env bash

# Update apt package index
sudo apt update

# Install nginx
sudo apt install -y nginx

# Define the custom 404 page content
NOT_FOUND_PAGE=$(cat <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>
EOF
)

# Create a custom 404 error page
echo "$NOT_FOUND_PAGE" | sudo tee /var/www/html/custom_404.html >/dev/null

# Configure Nginx to use the custom 404 error page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /custom_404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

# Test nginx configuration
sudo nginx -t

# Reload nginx to apply the changes
sudo systemctl reload nginx

