#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Displays the IP and HTTP status code.

awk '{print $1 " " $9}' https://intranet-projects-files.s3.amazonaws.com/holbertonschool-sysadmin_devops/80/apache-access.log
